vitessio/arewefastyet

ansible/roles/vitess-build/tasks/main.yml
Something is causing the build to fail when make is called without a shell environment. This changes it to use shell to call make rather then use the make module
=> Change Make invocation to use shell

ansible/roles/vitess-build/defaults/main.yml
The Golang version used to build Vitess has been upgraded to `1.15.3`. Additionally, the sha of `1.15.8` has been added for future uses.
=> switched to go 1.15.3 and addition of 1.15.8's sha

run-oltp, run-tpcc
This PR contains the required changes to run both OLTP and TPCC tasks from an OSX system.
The issue that OSX systems will encounter is defined here: https://github.com/ansible/ansible/issues/32499. And is fixed using their workaround (https://github.com/ansible/ansible/issues/32499#issuecomment-341578864).
=> enable runs on OSX systems

ansible/roles/vttablet/tasks/vttablet.yml
This PR introduces a fix to an issue happening when vttablet is created before (usually only a few seconds) MySQL has time to create its socket. When this happens, vttablet will fail to find the MySQL sockets, and thus future clients will not be able to use the vttablet.
The issue can be represented with the following log from vttablet:
```
E0212 07:15:02.389069   40885 tm_state.go:255] Cannot start query service: net.Dial(/vt/socket/mysql2001.sock) to local server failed: dial unix /vt/socket/mysql2001.sock: connect: no such file or directory (errno 2002) (sqlstate HY000)
```
To fix this, new ansible tasks for vttablet are added. These tasks, defined in `vttablet.yml`, split the creation of vttablet into two parts: MySQL and …
=> Wait for MySQL sockets to exist before creating vttablets

Makefile, docs/Installation.md, docs/Makefile.md, docs/README.md
Addition of a Makefile with these targets:
| Name        | Action           |
| ---------- | -------------- |
| `virtual_env`   | Check if virtualenv is present, if not, create it |
| `install`   | Call `virtual_env`, then install all depedencies (ansible & pip) |
| `oltp`   | Call `virtual_env`, then run an OLTP benchmark |
| `tpcc`   | Call `virtual_env`, then run a TPCC benchmark |
| `molecule_converge_all`   | Call `virtual_env`, then create a molecule and converge all the roles |
With the following variables:
| Name | Description | Default |
| ---- | ----------- | ------- |
| `PY_VERSION`   | Python version used | 3.7 |
| `VIRTUALENV_PATH`   | Path to virtualenv folder | benchmark |
| `ANSIBLE_PATH`   | Path to ansible …
=> Addition of Makefile

Makefile, docs/Makefile.md
This pull request resolves #38 by fixing the existing targets `oltp` and `tpcc` of the Makefile. They now use the CLI binary using setuptools install.
A new target is added, `install_dev_cli` enabling the dev/edit install of setuptools.
Changes were reported in the documentation.
=> Addition of missing install and outdated oltp/tpcc targets in Makefile

bench_cli/aws.py, bench_cli/cli.py, bench_cli/configuration.py, bench_cli/reporting.py, bench_cli/run_benchmark.py, bench_cli/task.py, bench_cli/zip.py, docs/cli.md, requirements.txt
After downloading and computing the report of a task, we now zip it and upload it to S3. We then generate a temporary link to the newly created object and send it over to the benchmark slack channel along with the report JSON.
The arborescence of the `tasks_reports_dir` has changed. Instead of dumping all the reports in `tasks_reports_dir`, we take it as a basepath and make new subdirectories from there. Now, each task has its own report subdirectory, making it easier to navigate through the different tasks and runs.
=> Tasks report zip and upload to S3

ansible/roles/vitess_build/tasks/main.yml, bench_cli/github_api.py, bench_cli/task.py, requirements.txt, test/unit/bench_cli/test_run_benchmark.py
Utilization of GitHub API through `PyGithub` to get more power out of the `--commit` CLI flag. We can now use the `--commit` flag with any reference (branch name, tag, partial commit SHA, release, pull request ID).
_**Example:**_
- `--commit "1"` will run the benchmarks on Vitess's pull request # 1
- `--commit "v9.0.0"` will run the benchmarks on Vitess's tag `v9.0.0`
- `--commit "79b93e2"` will run the benchmarks on Vitess's commit hash https://github.com/vitessio/vitess/commit/79b93e2215cf432678961beb0602fb9921629e19
- and so on ...
In addition to giving us more information, this start-off implementation of `PyGithub` allows us to implement more fancy features such as release report, commit status for each commit in Vitess.
- Resolves #56
- Resolves #57
=> Enable runs on pull request and any commit reference

bench_cli/run_benchmark.py, bench_cli/task.py
Integrated the `task.clean_up` method to the main loop of `BenchmarkRunner` and added options to delete the task's VPS, report directory, and artifacts.
=> Enhance cleanup step in BenchmarkRunner

go/infra/equinix/equinix.go, go/infra/infra.go, go/infra/infra_test.go
New CLI flag to specify the instance type used to provision a new Equinix device with terraform. This new flag is `--equinix-instance-type`.
The following content shall be added to the configuration file. Note that the instance type can be chosen from the list [here](https://metal.equinix.com/developers/docs/servers/).
```yaml
equinix-instance-type: t1.small.x86
```
#75
=> Specify instance type in Go CLI

.gitignore, go.mod, go.sum, go/cmd/root.go, go/cmd/web/web.go, go/server/server.go, go/server/server_test.go
Implementation of a `web` CLI command to start the HTTP server. The server will start using the above configuration (passed through config file or flags):
```yaml
web-port: 8080
web-template-path: ./go/server/templates
web-static-path: ./go/server/static
web-api-key: my_key
```
Additionally, `Server` is composed of a `mysql.ConfigDB` which will automatically be added to the `cobra.Command` when using the `Server`'s method `AddToCommand(cmd)`.
```sh
go run ./go/main.go --config config/config.yaml web
```
Resolves #86.
=> Link between the Go CLI and WebUI

go/mysql/mysql.go, go/server/handlers.go, go/server/mysql.go, go/server/server.go, go/server/templates/index.tmpl, go/server/templates/information.tmpl, go/server/templates/microbench.tmpl, go/server/templates/navigation.tmpl, go/server/templates/request_benchmark.tmpl, go/server/templates/search_compare.tmpl, go/tools/microbench/results.go, go/tools/microbench/results_test.go
This pull request adds a template to the UI allowing us to visualize microbenchmarks' results. A new set of functions and structures are added to the `microbench` package to allow computation of results.
In the picture below we can see the new template with a table, which was truncated in this picture. Each column showing results (`nanosecond/op`, `B/op`, ...) are divided into two sub-columns, the left one is the commit SHA for which we want to see the results, the right one is the results from another commit SHA. In this example, it refers to the V9.0.0 version.
For demonstration purposes, the commit SHA can be modified through the URL using parameters `csh` (current SHA) and `lrsh` (last release SHA).
The red and green respectively show if we have a lower or higher performance. The …
=> Preprocessing of microbenchmark results and render in web UI

go/cmd/exec/exec.go, go/exec/exec.go, go/infra/equinix/equinix.go, go/infra/infra.go, go/infra/infra_test.go
Resolves #99 by adding a `CleanUp` method to both the `Exec` struct and the `Infra` interface. In both places, the method will be responsible for cleaning up the post-execution.
The code in the pull request handle the destruction of the infrastructure.
=> Destroy terraform infrastructure after running an exec command

.github/workflows/golang_build.yaml, .github/workflows/golang_tidy.yaml, .github/workflows/golang_unit_test.yaml, go.sum
This pull request proposes three new workflows:
- `Golang Unit Tests`
- `Golang Build CLI`
- `Golang Tidy`
They all aim to validate or invalidate any new golang code that we push. `Golang Unit Tests` runs all the unit tests from the `./go` directory and its subdirectories. `Golang Build CLI` builds the CLI's binary. Finally, `Golang Tidy` will run a go mod tidy and fails if the repository needs to be tidied up.
All workflows are executed on go 1.15.
Resolves #98.
=> Addition of unit test and go mod tidy to GitHub Actions workflow

go/tools/math/median.go, go/tools/math/median_test.go, go/tools/microbench/results.go, go/tools/microbench/results_test.go
Previously, we integrated two functions that compute the median of integer/float arrays. These functions were added in the `go/tools/microbench` package inside the `results.go` file since we were using them only from there.
This pull request removes those two functions from the `go/tools/microbench` package and exports them inside the new `go/tools/math` package.
This change is required to respect DRY principle and enhance our testing policy.
Originally, the two functions' signatures were:
```go
func medianFloat(values []float64) float64
```
```go
func medianInt(values []int) int
```
Though, during testing, I realized that returning `int` for `medianInt` was incorrect, we need to return `float64` and let the caller cast or not the value to an `int`. Thus, the newly updated signatures are: …
=> New math package

go.mod, go/slack/config.go, go/slack/slack.go, go/slack/slack_test.go
This pull request tries to solve the issue with Slack mentioned in #104. It seems that the issue could be fixable by looking at the Vitess OSS Slack "vitess-benchmark" app configuration.
The app we were previously using "vitess-benchmark" was deactivated and could not be used. I created a new one "arewefastyet" and added it to Vitess OSS Slack with @askdba. The new OAuth token was then used in the YAML configuration file to authenticate new requests.
The `./go/slack` package underwent slight modifications. Support for Cobra command line was added to the `Config` (previously `config`) struct.
The following fields are appended to the configuration file:
```yaml
slack-token: <your app's token>
slack-channel: <your channel>
```
Fixes #104.
=> Fix: send slack messages

ansible/roles/vitess_build/tasks/clean.yml, ansible/roles/vitess_build/tasks/main.yml
The issue fixed in this pull request is linked to the idempotence step of `molecule test`. The `Molecule Test vitess_build` workflow started to fail due to the role `vitess_build` not being idempotent. More on that [here](https://github.com/vitessio/arewefastyet/actions/runs/718746242).
The error was the following:
```
--> Action: 'idempotence'
ERROR: 
PLAY [Converge] ****************************************************************
An error occurred during the test sequence action: 'idempotence'. Cleaning up.
```
The fix is a new condition on the block of tasks where we fetch Vitess's repository and build its binaries. The condition checks if the repository already exists in the system. Doing so allows us to skip unnecessary steps and thus making the role idempotent.
=> Fixed idempotence issue with Vitess Build and Ansible

ansible/roles/vtgate/templates/vtgate.conf.j2, ansible/roles/vttablet/templates/vttablet.conf.j2
Fixing a vtgate/vttablet configuration issue. The feature implemented in Vitess allowing us to start and stop profile recording at any time using `USR1`, [PR 7616](https://github.com/vitessio/vitess/pull/7616), was not correctly implemented in arewefastyet's side, resulting in recording starting way too early and finishing at inappropriate times. Thanks @vmg for finding this buggy behavior 🙏🏻
=> Addition of waitSig for vtgate/vttablet profiling

ansible/roles/microbench/tasks/main.yml, ansible/roles/vitess_build/tasks/install_vitess.yml, ansible/roles/vitess_build/tasks/main.yml
This pull request proposes a fix for #122. The faulty code is:
https://github.com/vitessio/arewefastyet/blob/5ef4b2b8c5770c2be3366bce2b7019a941e86878/ansible/roles/vitess_build/tasks/install_vitess.yml#L22
https://github.com/vitessio/arewefastyet/blob/5ef4b2b8c5770c2be3366bce2b7019a941e86878/ansible/roles/microbench/tasks/main.yml#L37
Adding an `else` statement in these single-line Jinja conditions fixes the issue.
Fixes #122.
=> Fix: vitess_build fetch updated vitess task error

go/infra/equinix/equinix.go
After upgrading to TF 0.15 the following error appeared and was caused by the use `tfexec.LockTimeout("60s")` as detailed in https://github.com/hashicorp/terraform-exec/issues/163
```
-lock, -lock-timeout, -verify-plugins, and -get-plugins options are no longer available as of Terraform 0.15: unexpected version 0.15.0 (min: -, max: 0.15.0)
```
Fixes #127.
=> Updated terraform init options list

ansible/microbench_inventory.yml
Changed the default Vitess package used by microbenchmark from `./go/vt/sqlparser/...` to `./go/vt/...`.
=> Changed default vitess package for microbenchmark

ansible/macrobench.yml, ansible/macrobench_sharded_inventory.yml, ansible/macrobench_unsharded_inventory.yml, ansible/roles/macrobench/tasks/main.yml, ansible/roles/sysbench/tasks/main.yml, docs/arewefastyet.md, docs/arewefastyet_macrobench.md, docs/arewefastyet_macrobench_run.md, go/cmd/macrobench/macrobench.go, go/cmd/macrobench/run.go, go/cmd/root.go, go/server/templates/index.tmpl, go/tools/macrobench/config.go, go/tools/macrobench/macrobench.go, go/tools/macrobench/macrobench_test.go, go/tools/macrobench/results.go, go/tools/macrobench/steps.go, go/tools/macrobench/steps_test.go, go/tools/macrobench/types.go, go/tools/macrobench/types_test.go
This pull request adds a new command to the CLI. The command allows us to execute a macro benchmark independently. Just like what we already do for `microbench`, we will not have to **only** go through the `exec` command in order to start macro benchmarks.
I came up with four main reasons why we need to implement this change. _First_ of all, it offers more consistency in the codebase, we were already treating micro benchmark with a unique command, so why not macro benchmark. _Secondly_, it allows easy local debugging and increases reproducibility, there is no need to spin up the infrastructure and wait for it to be configured. _Thirdly_, it enables us to deal with results and errors in a better way, everything is executed and controlled within the Golang code, not third-party shell …
=> Add a macro benchmark command

go/server/api.go
As the `git_ref` value given to `Exec` is not dynamic yet, new webhook executions will be limited to push events having a `refs/heads/master` ref. This will greatly reduce the number of Equinix Metal instances that we spin up until we are able to re-use instances in a more sustainable manner.
=> Ensure webhook payload push ref is set to refs/heads/master

go/tools/macrobench/results.go
Shortly after the migration process for [`001`](https://github.com/vitessio/arewefastyet/blob/master/sql/migration/001_New_parent_table_for_executions_125.sql) (PR #125) completed, non-fatal errors appeared on arewefastyet's production server and were causing macro benchmark dashboards unavailability.
```
2021-04-23T12:30:38.591Z        WARN    server/handlers.go:49   Error 1054: vtgate: {DB_HOST_NAME}: target: benchmark.-.master, used tablet: {VTTABLET_NAME} ({VTTABLET_IP}): vttablet: rpc error: code 
= NotFound desc = Unknown column 'b.test_no' in 'field list' (errno 1054) (sqlstate 42S22) (CallerID: vitess): Sql: "select b.test_no, b.`
commit`, b.source, b.`DateTime`, macrotype.tps, macrotype.latency, macrotype.errors, macrotype.reconnects, macrotype.`time`, macrotype.thr
eads, …
```
=> Hotfix invalid MySQL SELECT

go/exec/cmd.go, go/mysql/flags.go, go/server/api.go, go/tools/git/git.go
This pull request adds an `AddToViper` method to `mysql.ConfigDB` allowing execution to use MySQL configurations when triggered from webhooks. The execution source and git ref are also added to the handler. The source defaults to `webhook`, and the git ref is fetched using `go-git` and the reference located in the payload of the webhook query.
=> Configuration improvements on the webhook api handler

go/exec/exec.go, go/exec/provision.go, go/infra/equinix/equinix.go, go/infra/infra.go, infra/terraform/main.tf, infra/terraform/variables.tf
Addition of tags and unique names for our Equinix Metal instances with Terraform. The hostname is the UUID of the execution. The updated terraform state with the new hostname and tags is shown below:
```tf
resource "metal_device" "node" {
...
created                          = "2021-05-10T21:02:35Z"
deployed_facility                = "ams1"
facilities                       = [
"ams1",
]
hostname                         = "1d99b690-d81d-4cd6-bc3d-62975954c756"
...
operating_system                 = "centos_8"
plan                             = "m2.xlarge.x86"
...
tags                             = [
"local_test",
"918ce3d",
]
...
}
```
Resolves #141
=> Add tags and proper name to Equinix Metal instances

infra/cron/cron.sh, infra/cron/cron.txt
Addition of a cron to remove old execution directories. Each directory that's 1 year old will be removed.
To add the corn to crontab:
```sh
cd ./infra/cron
./cron.sh
```
Fixes #171.
=> Remove old execution directories

docs/arewefastyet_web.md, go/exec/exec.go, go/exec/status.go, go/server/cron.go, go/server/server.go, go/tools/git/github.go, go/tools/git/github_test.go, go/tools/macrobench/compare_test.go
A new cron job is added to the server, the job fetches the head's SHA of Vitess' pull requests matching a certain label (by default `Benchmark me`). Once we have the SHAs, we verify which type of benchmark (oltp, tpcc, micro) we need to execute for each SHA and execute a benchmark accordingly, we do not run the same benchmark twice on the same SHA.
Fixes #173.
=> Add label to Vitess PR to automatically request benchmarks

docs/arewefastyet_web.md, go/server/server.go, go/server/server_test.go
Remove the API key parameter in the server and CLI documentation. Webhooks and API are deprecated since #162.
Resolves #177.
=> Deleted unused api-key parameter in the server

go.mod, go/tools/git/git_test.go
This PR ports tests from `testify` to `quicktest` for consistency.
Resolves #180
=> Ports tests from testify to quicktest for consistency

go/cmd/microbench/run.go, go/exec/exec.go, go/server/handlers.go, go/tools/microbench/compare.go, go/tools/microbench/compare_test.go, go/tools/microbench/config.go, go/tools/microbench/line.go, go/tools/microbench/line_test.go, go/tools/microbench/microbench.go, go/tools/microbench/microbench_test.go, go/tools/microbench/results.go, go/tools/microbench/results_test.go, go/tools/report/compare_report.go
Changed the naming throughout `microbench` package, removed redundant names such as: `microbench.MicroBench()` and `microbench.CompareMicroBenchmarks`.
Fixes #138.
=> Changed redundant methods and fields naming in the microbench package

go/server/handlers.go, go/server/templates/compare.tmpl, go/server/templates/microbench.tmpl, go/server/templates/microbench_single.tmpl, go/server/templates/search.tmpl, go/tools/microbench/compare.go, go/tools/microbench/compare_test.go, go/tools/microbench/results.go, go/tools/microbench/results_test.go, go/tools/report/compare_report.go
This PR augments the webserver to display the results of the sub-benchmarks separately and not part of the same microbenchmark.
After this PR, the `microbenchmark` page will look like this - 
Also, the `microbenchmark/:name` page will now take a `subBenchmarkName` as a query argument and show results for a sub-benchmark
- Resolves #161
=> Adds support to track microbenchmarks as distinct sub-benchmarks

ansible/roles/macrobench/tasks/main.yml, docs/arewefastyet_exec.md, go/exec/cmd.go, go/exec/exec.go, sql/migration/004_add_pull_request_to_execution.sql, sql/migration/test_migration.sh, sql/vitess-benchmark.sql
Our ansible scripts supports the execution of macro and micro benchmarks on pull request, since pull request commits are outside of the regular tree, they need to be fetched using specific git fetch syntax like: `git fetch origin refs/pull/PR_NUMBER/head`.
Link between Execution's golang code and Ansible is added through this pull request, we define if the execution is linked to a pull request or not through a new integer CLI flag, its value is the pull request number. If we declare that the execution is linked to a pull request, then the proper git fetch ref spec is added to Ansible's ExtraVars.
Fixes #178.
=> Add pull request information in execution and Ansible ExtraVars

go/server/cron.go
Master cron job does not check if there are existing runs for the same sha. This would happen when there were no commits on Vitess on a given day. In this case, we would not want to run the cron jobs for the same sha. This PR adds a check for it.
Fixes #190
=> Adds check for master cron job to check if there are existing runs for the same sha

go/exec/exec.go, go/exec/exec_test.go
In the regression slack message that we send, instead of just having the results, we would also want to add the link to the website where the comparison can be graphically seen. This PR adds this functionality
Fixes #193
=> Addition of link for comparison in slack message

infra/monitoring/files/dashboards/cluster_overview.json, infra/monitoring/files/dashboards/keyspace_overview.json, infra/monitoring/files/provisioning/ansible.yaml, infra/monitoring/playbook.yaml
This pull request adds two new dashboards to the Grafana server. The new dashboards originate from [vitess-mixin](https://github.com/vitessio/vitess/tree/master/vitess-mixin), on both of them, a new variable is added to allow ad-hoc filtering, so that results can be filtered by `exec_uuid`. Below is a representation of what the two dashboards look like.
**Keyspace overview:**
**Cluster overview:**
Resolves #185.
=> Addition of vitess-mixin dashboards in Grafana

go/tools/git/git.go, go/tools/git/git_test.go
This pull request shows only RC and recent tags in comparison dropdowns. Only tags above or equal to Vitess's version 7.0 will be shown.
Resolves #202.
=> Use recent and RC tags for macro/micro comparison

go/server/handlers.go, go/tools/git/git.go
This pull request fixes the way we order git release tags.
The order before:
- 10.0.0
- 10.0.0-rc1
- 10.0.1
- 7.0.0
- 7.0.1
- ...
- 9.0.1
- master
The order now:
- master
- 10.0.1
- 10.0.0
- 10.0.0-rc1
- 9.0.1
- ...
- 7.0.1
- 7.0.0
=> Patched release tags ordering

go/server/cron.go, go/server/handlers.go, go/tools/git/git.go, go/tools/git/git_test.go
This PR adds the ability to run CRONs for release branches as well. This will enable us to track any regression in case of bug fixes that go into the release branches.
Fixes #208
=> Cron for release branches

go/tools/git/git_test.go
Unit test for the proper ordering of git release tags which was introduced by #205.
=> Addition of unit test for git releases ordering

go/cmd/exec/exec.go, go/exec/exec.go, go/server/cron.go
The clean-up phase of the execution was overriding the status of execution in the database, the new defer statement and the Success method fix that issue.
=> Fixing clean up defer statement with new Success method

go/server/handlers.go
This PR adds the release branches to the website as well so that the results of the ran cron jobs can be seen.
Fixes #211
=> Add release branches to the website

go/exec/metrics/metrics.go, go/exec/metrics/metrics_test.go, go/server/server.go, go/server/templates/compare.tmpl, go/server/templates/macrobench.tmpl, go/server/templates/search.tmpl, go/tools/macrobench/results_test.go
This pull request provides initial support for golang's memory metrics. The metrics we're fetching and analyzing are `go_memstats_alloc_bytes_total`. In the future, it would be preferable to have a very flexible way of adding and modifying the golang metrics we want to fetch & compute.
The metrics are fetched in the execution metrics package and appended to macrobenchmark's comparison and details. The metric is stored for both VTGate and VTTablet, the sum of the two is also stored.
Resolves #216.
=> Golang memory allocs metrics support

ansible/macrobench.yml, ansible/macrobench_sharded_inventory.yml, go/exec/exec.go, infra/terraform/main.tf, infra/terraform/variables.tf, requirements.txt
This pull request fixes an issue with TPCC's vschema, in short, TPCC vschema was not properly set and was using OLTP's vschema instead. This issue is fixed by introducing two Ansible variables (`macrobenchmark_vschema_oltp` and `macrobenchmark_vschema_tpcc`) that define which vschema file needs to be used.
Additionally, the execution type (oltp, tpcc, micro) is added to Equinix instances' tags.
Resolves #218.
=> Support for oltp/tpcc vschema and improved equinix tags

ansible/roles/macrobench/tasks/main.yml, ansible/roles/vtgate/templates/vtgate.conf.j2, docs/arewefastyet_exec.md, docs/arewefastyet_macrobench_run.md, go/exec/cmd.go, go/exec/exec.go, go/server/cron.go, go/tools/macrobench/config.go, go/tools/macrobench/macrobench.go, infra/terraform/main.tf, infra/terraform/variables.tf, sql/migration/005_add_vtgate_planner_version_to_macrobenchmarks.sql, sql/migration/test_migration.sh, sql/vitess-benchmark.sql
This PR adds a new flag to the execution of macrobenchmarks which allows us to change the planner version that vtgate is using - (V3, Gen4Fallback). It also updates the cron jobs to run for both versions for planner.
Finally, it adds additional tags to the equinix servers that are running.
Fixes #214
=> Planner Version Support in Macrobenchmarks

go/exec/exec.go, go/server/handlers.go, go/server/server.go, go/server/templates/index.tmpl, go/server/templates/navigation.tmpl, go/tools/macrobench/compare.go, go/tools/report/compare_report.go
This pull request adds a switch to change which vtgate planner we want to use to query results on the website. The default is to use V3 planner, but can be switched to `Gen4Fallback` by turning the switch on.
=> Switch between vtgate planner V3 and Gen4

go/exec/metrics/metrics.go, go/exec/metrics/metrics_test.go
Fixing a use case where `metrics.compareSafeComponentMap`'s left map is empty and caused the output to be empty as well.
=> Fixing compareSafeComponentMap when left map is empty

go/exec/exec.go
The changes brought by this pull request will allow the notification of each PR execution as well as an enhanced message for PR executions. Regardless of possible regressions, a notification will always be issued.
Fixes #215.
=> Send Slack notification on every PR execution

go/server/templates/navigation.tmpl
Simpler navigation names in the header:
**Before**
**Now**
=> Simpler navigation names

go/server/handlers.go
The first time the website is accessed, the `vtgatePlanner` cookie is not set. For now, we would throw a warning when this happened. The behavior has been changed to just return the default.
Fixes #232
=> Set cookie default instead of warning

.gitignore, infra/monitoring/playbook.yaml, infra/monitoring/roles/influxdb/tasks/main.yaml
Changing the `max-series-per-database` configuration to `0` (unlimited). The default value (1000000) got reached pretty fast and was causing an outage, the default retention policy will handle old results.
The error we got is written below and documented [here](https://docs.influxdata.com/influxdb/v1.8/troubleshooting/errors/#error-max-series-per-database-exceeded--).
```
error: max series per database exceeded: < >
```
=> Changing InfluxDB default settings for max-series-per-database 

docs/README.md, docs/arewefastyet_exec.md, docs/arewefastyet_web.md, docs/cron.md, go/exec/cmd.go, go/exec/exec.go, go/server/cron.go, go/server/notification.go, go/server/notification_test.go, go/server/server.go, go/tools/git/git.go, go/tools/git/github.go
This PR refactors the cron jobs to allow running multiple regression checks. The changes made also guarantee that when a regression message is sent, both the sources have finished execution.
Fixes #231
=> More regression runs

go/tools/git/git_test.go
The test `TestGetAllVitessReleaseCommitHashOrdering` relied on having few releases one after the other in the result set but this invariant is broken with the release of 9.0.2 on Vitess. This PR relaxes this test to also pass if the required releases are not one after the other as long as they are present in the result in the correct order.
Fixes #238
=> Fixes TestGetAllVitessReleaseCommitHashOrdering

go/exec/exec.go, go/infra/equinix/equinix.go, go/server/cron.go
This pull request enhances the clean-up and execution workflow for cron jobs. A new method is added to exec: `ExecuteWithTimeout(timeout time.Duration)`, this method wraps the original `Execute` method with a timeout that will stop the execution if `timeout` is reached. The clean-up step is enhanced by adding the [flag](https://www.terraform.io/docs/cli/commands/init.html#lock-timeout-lt-duration-gt-) `-lock-timeout=<duration>` to Terraform's destroy command. This flag allows us to wait for terraform state's lock to be unlocked before attempting to destroy the resource, this tweak is useful in the event where we have to destroy our Equinix Metal instance even though its provision is not complete.
=> Execute With Timeout and enhanced clean up

go/storage/influxdb/config.go, go/tools/macrobench/endtoend/compare_test.go
This pull request adds an E2E test and two benchmarks for the CompareMacroBenchmarks function. This function was the source of suspicions regarding an extended loading time for the `/macrobench` and `/compare` web page. In fact, those endpoints take a few seconds to answer. @GuptaManan100 and I initially thought the time was lost in the CompareMacroBenchmarks method, the added microbenchmarks prove that this fact is true.
```
goos: darwin
goarch: amd64
pkg: github.com/vitessio/arewefastyet/go/tools/macrobench/endtoend
cpu: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
BenchmarkCompareMacroBenchmark
BenchmarkCompareMacroBenchmark/Gen4_planner
BenchmarkCompareMacroBenchmark/Gen4_planner-16         	       1	3476018355 ns/op	 3402888 B/op	   11923 allocs/op …
```
=> Benchmarks and E2E test for CompareMacroBenchmarks

ansible/roles/macrobench/tasks/main.yml, ansible/roles/vtgate/templates/vtgate.conf.j2, docs/arewefastyet_web.md, go/exec/exec.go, go/server/cron.go, go/server/server.go, go/tools/git/github.go
This pull request resolves various bugs and a feature request, all of them are detailed in #241.
- VTGate's `-planner_version` flag is used only when the git ref used is recent enough and includes the flag, meaning that git ref below V10.0.0 will not be benchmarked using the Gen4 planner.
- Only send slack notifications for comparisons that are new and do not repeat the same message that we have already sent earlier.
- Currently, the benchmarks are running for the same configuration multiple times. This issue arises because we are only testing `ifExists` for `finished` benchmarks while spawning new ones and not the ones which are in execution.
Resolves #241.
=> Fix Cron Jobs

go/server/cron.go, go/server/git.go, go/server/handlers.go
Applying the changes brought by vitessio/vitess#6378, renaming vitess's default branch from `master` to `main`.
=> Migration of vitess default branch from master to main

go/server/templates/footer.tmpl, go/server/templates/microbench_single.tmpl
Changing `Allocs` to `Allocations` and `MB` to `Megabytes` on the single-microbench page, and changed `2020` to `2021`.
=> Changed single microbenchmark table header and year in footer

go/server/templates/navigation.tmpl
Addition of a tooltip around the Gen4 toggle to ease understandability and navigation.
=> Tooltip on gen4 toggle to ease navigation

ansible/roles/vitess_build/molecule/all/molecule.yml, ansible/roles/vitess_build/tasks/mysql.yml, requirements.txt
Upgrade ansible to `2.9.20`, enabling the fix of a bug related to `systemd` (https://github.com/ansible/ansible/pull/72337 and https://github.com/ansible/ansible/issues/71528). The upgrade brought up a new bug related to GPG keys, which was fixed using this https://github.com/ansible/ansible/pull/71640.
The issue with `systemd` was impacting all ongoing pull requests' status.
=> Upgrading Ansible from 2.9.11 to 2.9.20

ansible/roles/vtgate/templates/vtgate.conf.j2
This pull request adds the `tablet_types_to_wait` flag to VTGate, the internal usage of the flag was modified by vitessio/vitess#8218. Not providing tablet types to wait provokes the following error:
```
tablet_types_to_wait flag must be set
```
=> Addition of tablet_types_to_wait flag to vtgate's configuration

docs/arewefastyet_macrobench_run.md, docs/arewefastyet_web.md, go/cmd/macrobench/run.go, go/exec/metrics/endtoend/main_test.go, go/exec/metrics/metrics.go, go/server/handlers.go, go/server/notification.go, go/server/server.go, go/server/storage.go, go/tools/macrobench/compare.go, go/tools/macrobench/config.go, go/tools/macrobench/endtoend/compare_test.go, go/tools/macrobench/macrobench.go, go/tools/macrobench/results.go, go/tools/report/compare_report.go, sql/migration/007_metrics_table.sql, sql/vitess-benchmark.sql
This pull request changes the way we store and use execution metrics. Previously read from influxdb when using them in the web server, they are now read from a SQL database; this will increase the website performance. To be read from a SQL database, they are first written there at the end of each `macrobench run` call. The macrobenchmark toolset handles storing metrics to SQL.
A new table `metrics` has been added. It represents a key/value table with the name of the metric and its value (a float). Each metric is linked to an execution ID and has a unique primary key.
Resolves #248.
=> Compute and store execution metrics after each execution

go/server/handlers.go
Changes the default order of the columns in the UI's result tables. The latest commit (on `main`) is now on the right-hand side of the table, allowing the `Improved by %` column to reflect the changes from the `latest release` to `main`.
**Before:**
**After:**
=> Changed the ordering of columns in webserver result tables

ansible/roles/vtgate/templates/vtgate.conf.j2, ansible/roles/vttablet/templates/vttablet.conf.j2, go/exec/exec.go, go/server/cron.go
This pull request enables vtgate and vttablet schema tracking feature if we execute a macro benchmark through the nightly cron of type `cron`. This aims to test and ensure the stability of the changes brought by https://github.com/vitessio/vitess/pull/8074. Since we do not perform any DDL during our benchmarks, schema tracking should not impact performance, this pull request will confirm it.
=> Enable schema tracking in vttablet and vtgate on main cron

go/server/templates/v3VsGen4.tmpl
The graphs used to render the results of v3vsGen4 macrobenchmarks had their columns inversed, and thus not matching the data they were being labeled for. This pull request fixes that.
**Before:**
**Now:**
=> Fixing v3vsGen4 macro benchmark results graphs order

go/exec/exec.go, go/exec/metrics/metrics.go, go/tools/macrobench/results.go, go/tools/microbench/results.go
Closing rows fetched after calling `SQLClient.Select`. This reduces the number of fd opened concurrently and solves the issue mentioned in #253.
Fixes #253.
=> Closing rows after select

go/tools/macrobench/results.go, go/tools/macrobench/results_test.go
Small fix to change the way we calculate the `Improved by %` for the `Errors` field. If the recent version has `Errors` higher than the old version then the `Improved by %` column should be negative.
**Before**
**After**
=> Fixed improved by % for the macrobenchmark errors

ansible/roles/vitess_build/defaults/main.yml, go/exec/cmd.go, go/exec/exec.go, go/server/cron.go
This pull request bumps the golang version used for the benchmarks to `go1.17` and improves the way we configure pull request numbers when executions are triggered by the `cron_pr` cron.
=> Migrated to Go 1.17 and better setup of PR numbers during CRONs

go/server/handlers.go, go/tools/microbench/results.go
- Applying an `order by date` on the single microbenchmark results matrix before rendering it
- Swapping the `current` and `last` result columns on the `microbench` page
=> Fixed date and order rendering issue for single microbenchmarks

.github/workflows/deploy.yml
This pull request updates the default branch of arewefastyet in the Deploy workflow from `master` to `main`.
=> Update the default branch to main in the `Deploy` workflow

go/server/cron_handlers.go, go/server/logger.go, go/server/server.go, go/server/server_test.go
This pull request alleviates an issue that appeared in the log of our web server when two concurrent threads were updating the local clone of Vitess.
Sample of the error:
```
cannot lock ref 'refs/remotes/origin/main': is at 8245b11cb511fde9de7adb9c73fa551f05c5582e but expected f2663ec9e54c60445d77545a5387b0130ffd5762
From https://github.com/vitessio/vitess
! f2663ec9e5..8245b11cb5  main         -> origin/main  (unable to update local ref)
error: cannot lock ref 'refs/remotes/origin/mp-help-fix': is at fadc4e2abd4906b7913b99a58a55972ca9f00149 but expected 2dc6cc72082e697561e5c66d3fa4a6702dcd5c13
! 2dc6cc7208..fadc4e2abd  mp-help-fix  -> origin/mp-help-fix  (unable to update local ref)
error: cannot lock ref 'refs/remotes/origin/release-12.0': is at aee4b9c0aa8e57244b7b7df72584021495337dce …
```
=> Fix concurrent pull/fetch in the Vitess repository

.github/workflows/deploy.yml, .github/workflows/molecule-all.yml, .github/workflows/molecule-etcd.yml, .github/workflows/molecule-vitess-build.yml, .github/workflows/molecule-vtctld.yml, .github/workflows/molecule-vtgate.yml, .github/workflows/molecule-vttablet.yml, ansible/roles/vitess_build/tasks/main.yml
This pull request changes how the deploy workflow uses the `go` binary. Instead of calling `go` using the absolute path, it simply uses the `PATH`.
=> fixed the path to the golang binary in the deploy workflow

ansible/roles/vtctld/tasks/systemd.yml, ansible/roles/vtgate/tasks/systemd.yml, ansible/roles/vttablet/tasks/systemd.yml
In certain cases where the `vtgate` service file (`/etc/systemd/system/vtgate@.service`) was present but was not reloaded using systemd, Ansible would skip the reload, and thus any `vtgate@*` service would fail to start.
This pull request fixes that issue by not skipping the reload.
=> Don't skip systemd reload for vtgate, vttablet and vtctld

ansible/roles/vitess_build/tasks/main.yml
An issue appeared when running the `vitess_build/main` task in the production environment where golang was not able to stat the temporary build directory: `creating work dir: stat ~/tmp: no such file or directory`.
To fix this issue, this Pull Request changes the path (`~/tmp`) to an absolute path: `/root/tmp`.
=> Use absolute path to set the temporary go build directory

ansible/roles/macrobench/tasks/main.yml, ansible/roles/microbench/tasks/main.yml
When can happen if the webserver responsible for the execution queue restarts, the ongoing benchmark will not be managed anymore, which leads to an issue where the `arewefastyetcli` binary is kept running on the benchmark server. Having the binary used does not allow us to write to the same file, the following error appears:
```
cp: cannot create regular file '/usr/bin/arewefastyetcli': Text file busy
```
This pull request ensure the `arewefastyetcli` binary is removed before creating a new one.
=> Remove old `arewefastyetcli` binary from the bin before updating it

ansible/roles/vitess_build/defaults/main.yml
This Pull Request changes the default value of the go version in `vitess-build`'s defaults.
Failing Ansible Molecule CI tests can be ignored.
=> Change go version default value in Ansible's vitess-build role

ansible/roles/macrobench/tasks/main.yml, go/server/cron.go, go/server/cron_handlers.go, go/server/handlers.go, go/server/templates/index.tmpl, go/server/templates/navigation.tmpl, go/tools/git/git.go, go/tools/macrobench/compare.go, go/tools/macrobench/macrobench.go
This Pull Request removes the execution of benchmarks using the `v3` planner, instead only `Gen4` benchmarks will be run (instead of `v3` & `Gen4Fallback`).
The visualization of results for both `v3` and `Gen4` is removed. Now we can only see the results for `Gen4`.
=> Remove the v3 planner from the list of execution and from the website

ansible/roles/vitess_build/defaults/main.yml
This PR upgrades the Go version used in the benchmarks to `go1.18.4`. This is a follow-up of the upgrade done on `vitessio/vitess` on https://github.com/vitessio/vitess/pull/10705.
=> Upgrade to Go 1.18.4

go/server/cron.go, go/server/cron_execution.go, go/server/templates/status.tmpl, go/tools/macrobench/macrobench.go
This Pull Requests removes duplicated benchmarks in the execution queue web page and removes elements from the queue as soon as they are done being executed.
=> Improve how elements in the execution queue are handled

ansible/roles/vtctld/files/vtctld@.service, ansible/roles/vtctld/templates/cell@.service.j2, ansible/roles/vtctld/templates/vtctld@.service.j2, ansible/roles/vtgate/templates/vtgate.conf.j2, ansible/roles/vtgate/templates/vtgate@.service.j2, ansible/roles/vttablet/templates/mysqlctld@.service.j2, ansible/roles/vttablet/templates/vttablet.conf.j2, ansible/roles/vttablet/templates/vttablet@.service.j2
This Pull Request changes the flag syntax used to create the different Vitess services. The syntax has changed in v14 to use `--flag` instead of `-flag`. In v15/main it is now mandatory, without the new syntax the benchmarks were failing.
=> Update the flag syntax used to create Vitess services

ansible/create_cluster.yml
This PR changes how we apply VSchema. Depending on the running Vitess version, different flags will be used.
=> Apply VSchema differently based on the vitess version

ansible/microbench_inventory.yml
This PR changes the scope of the microbenchmarks. Instead of running only on `./go/vt/...` they will now run on `./go/...`.
=> Run all the microbenchmarks located in `./go/...`

config/benchmarks/oltp-set.yaml
This PR enables settings pool for oltp-set benchmark for 15.0 onwards
=> enable settings pool for oltp-set benchmark

config/dev/config.yaml, config/prod/config.yaml, docs/arewefastyet_web.md, go/server/cron.go, go/server/server.go
This PR adds a new flag to the server to exclude certain sources from the list of benchmarks we execute in the cron. `"cron_tags_14.0.0-rc1"` is removed as it does not build due to incorrect flags.
=> Addition of a flag to exclude some source from the crons

.github/workflows/deploy.yml
This PR fixes an issue that happens when trying to deploy new changes with the deploy workflow. The issue can be seen in https://github.com/vitessio/arewefastyet/actions/runs/3141082170/jobs/5103135373, the go build command fails because the go binary cannot be located.
=> Set the golang bin path when deploying new changes

ansible/roles/vitess_build/tasks/main.yml, ansible/roles/vtctld/tasks/clean.yml, ansible/roles/vttablet/tasks/clean.yml
This PR improves the cleaning phase of VTTablet and VTctld by clearing out the vitess binaries to avoid the following error:
```
$> make install PREFIX=/usr/local VTROOT=/go/src/vitess.io/vitess
Thu Sep 29 02:35:52 UTC 2022: Building source tree
cp: cannot create regular file '/usr/local/bin/vtctlclient': Text file busy
make: *** [Makefile:140: install] Error 1
```
=> Improve the cleaning phase of vttablet and vtctld

go/tools/macrobench/vtgate.go
This PR fixes a panic that happens when trying to normalize a query plan that contains values equal to 0. This PR is to unblock the production server from benchmarking new/past commits.
I will investigate why we are getting ExecCount = 0 in some cases.
Here is a trace of the observed panic:
```
panic: runtime error: integer divide by zero
goroutine 1 [running]:
github.com/vitessio/arewefastyet/go/tools/macrobench.normalizeVTGateQueryPlan(...)
```
=> Avoid division by 0 when normalising VTGate query plan results

config/benchmarks/olap-readonly.yaml, config/benchmarks/oltp-readonly.yaml, config/benchmarks/oltp-set.yaml, go.mod, go/exec/exec.go, go/server/cron.go, go/server/cron_execution.go, go/server/cron_handlers.go, go/server/server.go
This PR adds the field `minimum-version` to the configuration file of a benchmark. The value of this field will tell us on which minimum **major** version of Vitess the given benchmark should run.
```yaml
minimum-version: 14 # -> will run only on v14.0.0 and above
```
=> Add `minimum-version` to benchmark configuration

ansible/macrobench_sharded_inventory.yml, ansible/macrobench_unsharded_inventory.yml, ansible/microbench_inventory.yml, ansible/roles/macrobench/tasks/main.yml, ansible/roles/microbench/defaults/main.yml, ansible/roles/microbench/tasks/main.yml, go.mod, go/exec/exec.go, go/server/cron_execution.go
This PR removes the previous arewefastyet repository from the disk before cloning it. It ensures we always get the most up to date version of arewefastyet.
=> Remove old arewefastyet repository folder

go/exec/exec.go, go/server/server.go
This PR fixes an issue that happened when assigning a viper configuration to a new execution. We used to change the main viper configuration always and assign the execution configuration to it. This PR creates a brand new configuration and assign the main + the execution configuration to it. This way the "merged" configuration is only used by this new execution.
=> Fix benchmark configuration copy

config/benchmarks/micro.yaml, config/benchmarks/olap-readonly.yaml, config/benchmarks/oltp-readonly.yaml, config/benchmarks/oltp-set.yaml, config/benchmarks/oltp.yaml, config/benchmarks/tpcc.yaml, docs/arewefastyet_exec.md, docs/arewefastyet_macrobench_run.md, go/cmd/exec/exec.go, go/infra/ansible/ansible.go, go/infra/ansible/files.go, go/tools/macrobench/config.go, go/tools/macrobench/steps.go, go/tools/macrobench/steps_test.go
This PR fixes an error where the `ansible-inventory-file` and `ansible-playbook-file` configuration were not merged correctly. Since those configuration are used only with string instead of a slice of strings, I have changed them to be a `string` instead of a `[]string`.
=> Fix configuration error for Ansible file paths

ansible/roles/vttablet/templates/mysqlctld@.service.j2
This PR removes a deprecated flag that was preventing the mysqlctld service from starting up. The issue was visible in vttablet's logs as the mysql data directory was not created:
```
F1010 07:25:56.488927 1116548 vttablet.go:172] mycnf read failed: open /vt/vt/vt_1001/my.cnf: no such file or directory
```
=> removed the dbconfig flag in mysqlctld service

ansible/create_cluster.yml, config/benchmarks/olap-readonly.yaml, config/benchmarks/oltp-readonly.yaml, config/benchmarks/oltp-set.yaml, config/benchmarks/oltp.yaml, config/benchmarks/tpcc.yaml, docs/arewefastyet_exec.md, go/exec/cmd.go, go/exec/exec.go, go/infra/ansible/vars.go
This PR fixes an issue that was observed when running a `TPCC` benchmark and then the `SET` benchmarks. They were failing due to the VSchema not being here. This PR adds the VSchema information directly inside the benchmark configuration file.
=> Set the vschema in the configuration of the benchmarks

ansible/roles/vitess_build/defaults/main.yml, config/dev/config.yaml, config/prod/config.yaml
This PR upgrades the Go version that arewefastyet uses to `go1.18.7`.
=> Upgrade to Go 1.18.7

.github/workflows/deploy.yml, .github/workflows/golang_build.yaml, .github/workflows/golang_lint.yaml, .github/workflows/golang_tidy.yaml, .github/workflows/golang_unit_test.yaml, .github/workflows/verify_cli_documentation.yml, ansible/roles/vitess_build/defaults/main.yml, config/dev/config.yaml, config/prod/config.yaml
This PR changes the go version used in the benchmarks to `go1.19.4`.
=> Upgrade to `go1.19.4`

.github/workflows/ansible-lint.yml, ansible/roles/vtctld/templates/cell@.service.j2, ansible/roles/vtctld/templates/vtctld@.service.j2, ansible/roles/vtgate/templates/vtgate.conf.j2, ansible/roles/vtgate/templates/vtgate@.service.j2, ansible/roles/vttablet/templates/vttablet.conf.j2, ansible/roles/vttablet/templates/vttablet@.service.j2
This PR removes several flags that were used in vtctld even though they were recently removed from Vitess. And it adds support for the upcoming v16 release.
=> Remove deprecated vtctld flags and add `v16` support

config/prod/config.yaml
This PR skips, for now, the benchmarks made on `cron_tags_14.0.4`. They constantly fail due to compilation issue with `go1.19`.
=> Skip benchmarks on `cron_tags_14.0.4`

.github/workflows/deploy.yml, .github/workflows/golang_build.yaml, .github/workflows/golang_lint.yaml, .github/workflows/golang_tidy.yaml, .github/workflows/golang_unit_test.yaml, .github/workflows/verify_cli_documentation.yml, ansible/roles/vitess_build/defaults/main.yml, config/dev/config.yaml, config/prod/config.yaml, go.mod
In prevision of the upcoming go upgrade on `vitessio/vitess`, this PR upgrades the golang version used by our benchmarks to `go1.20.1`.
=> Upgrade to `go1.20.1`

go/tools/git/git.go
This PR fixes an important issue that, in certain cases, would not let us parse the version increment from the branch name correctly.
=> Fixes issues with regex when looking for release branch increment

.github/workflows/deploy.yml, .github/workflows/golang_build.yaml, .github/workflows/golang_lint.yaml, .github/workflows/golang_tidy.yaml, .github/workflows/golang_unit_test.yaml, .github/workflows/verify_cli_documentation.yml, ansible/roles/vitess_build/defaults/main.yml, config/dev/config.yaml, config/prod/config.yaml
This PR bumps the golang version used in our tests and in our benchmarks to `go1.20.3`
=> Bump golang version to `1.20.3`

website/index.html, website/package-lock.json, website/package.json, website/src/components/ExecutionQueue/ExeQueue.jsx, website/src/components/ExecutionQueue/exeQueue.css, website/src/components/PreviousExeResponsive/PreviousExeRes.jsx, website/src/components/PreviousExeResponsive/previousExeRes.css, website/src/components/PreviousExecutions/PreviousExe.jsx, website/src/components/PreviousExecutions/previousexe.css, website/src/pages/Status/Status.jsx, website/src/pages/Status/status.css
I redesigned the status page and its components from scratch, but this time I didn't use a table because the responsiveness wasn't optimized. Instead, I recreated the page for the desktop version by manually creating my own table using <div> elements and controlling their widths.
=> [Refactor] Redesign status page for improved responsiveness

go/server/api.go, go/server/server.go
This PR adds a route to the API to return the list of fields used by the macrobenchmark comparison.
=> add list of macrobenchmark fields to API

go/server/api.go, go/server/server.go, go/tools/macrobench/compare.go, go/tools/macrobench/results.go
This PR removes the `fields` endpoint from the API as it turns out to not be super useful. And it initialize the `nil` map fields of the execution metrics.
=> Remove `fields` API and init empty map fields

go/tools/macrobench/compare.go, go/tools/macrobench/endtoend/compare_test.go, go/tools/macrobench/results.go, go/tools/macrobench/results_test.go, go/tools/microbench/compare.go, go/tools/report/compare_report.go
This PR changes the labels `reference` and `compare` to `right` and `left`. The previous names were misleading.
=> Use `left` and `right` indicator instead of `reference`/`compare` in the API and backend code

go/server/api.go, go/server/server.go, go/server/templates/microbench.tmpl, go/tools/microbench/results.go, go/tools/microbench/results_test.go, go/tools/report/compare_report.go
This PR adds the `/api/microbench/compare` route to the API to enable comparison of microbenchmarks.
=> Add route to compare microbenchmarks through the API

go/server/api.go, go/server/server.go, go/tools/macrobench/vtgate.go
This pull request adds validation and error handling to the queriesCompareMacrobenchmarks function in the Server struct.
Validation is performed for the leftGitRef, rightGitRef, and macroType parameters. If any of these parameters are missing, a JSON response with a 400 (Bad Request) error code is returned, indicating that the required parameters are missing.
Additionally, error handling is added when calling the macrobench.GetVTGateSelectQueryPlansWithFilter functions. If an error occurs while retrieving the query plans, a JSON response with a 500 (Internal Server Error) error code is returned, containing the error message returned by the function, and the error is also logged.
Finally, the macrobench.CompareVTGateQueryPlans function is used to compare the obtained query plans. The …
=> Creation of the API for the 'query plan' page

config/dev/config.yaml, go/server/api.go, go/server/cron.go, go/server/cron_execution.go, go/server/cron_handlers.go, go/server/templates/status.tmpl
This PR changes the execution queue from a map to a slice in order to have an ordered data list.
=> Use `slice` instead of map for the execution queue

go/exec/status.go, go/server/api.go, go/server/server.go, website/package-lock.json, website/package.json, website/src/components/CRONComponents/CRONSummary/CronSummary.jsx, website/src/components/CRONComponents/CRONSummary/cronSummary.css, website/src/pages/Status/Status.jsx, website/src/pages/Status/status.css
This pull request introduces a new feature to retrieve benchmark statistics in the server's API. It includes updates to the codebase to fetch and provide benchmark statistics to the clients.
Changes Made:
Added a new struct benchmarkStats with three fields: Benchmark_total, Benchmark_finished, and Benchmark_30Days. This struct will hold the benchmark statistics.
Implemented the GetBenchmarkStats function which retrieves the benchmark statistics from the database using the provided SQLClient. It executes a SQL query to count the total number of benchmarks, the number of finished benchmarks, and the number of benchmarks within the last 30 days. The query results are then assigned to the respective fields of the benchmarkStats struct.
In the getStatusStats function of the Server struct, the …
=> Add Benchmark Statistics API Endpoint and Retrieval Functionality

website/src/components/QueryPlan/QueryPlan.jsx, website/src/pages/MacroQueriesCompare/MacroQueriesCompare.jsx
I changed the condition to display the data on the query plan page to avoid getting an error if any of the URL parameters is null.
=> Enhancement: Improved Handling of Null URL Parameters in Query Plan Display

website/src/pages/Macro/Macro.jsx
I simply added 'commitleft' and 'commitright' props to my 'macrobenchMobile' component because the link to the 'query compare' page was not functioning otherwise.
=> Fixing Query Compare Page Link and Adding 'commitleft' and 'commitright' Props to 'macrobenchMobile' Component

go/server/server.go
The `oltp-readonly-olap` has been consistently failing due to MySQL connections being dropped. Let's skip this benchmark for now to free the execution queue as much as possible while I investigate why the workload fails on Vitess.
=> Skip `oltp-readonly-olap`

config/prod/config.yaml, go/server/cron_handlers.go, go/server/server.go
Reverts vitessio/arewefastyet#462
=> Revert "wip test pr perf"

ansible/clean_macrobench.yml, ansible/macrobench.yml, ansible/roles/prometheus/tasks/update_uuid.yml, ansible/setup.yml
We used to re-start the Prometheus service between each benchmark (whether it was the same one or not) which led to Prometheus replaying the WAL after every restart and being unavailable to collect metrics during this time. This issue was not very visible before #517 as benchmarks were long, but since benchmarks run fairly fast now, the issue is obvious and leads to benchmarks having 0 metrics collected. Also this issue is not easily reproducible on the dev host machine as the whole setup of benchmark is a lot longer there.
With this PR we are not keeping Prometheus running all the time on the host machine and using hot reloading of the configuration files to change the `exec_uuid` label.
=> Fix lack of Prometheus metrics and improve reliability of collected metrics

ansible/macrobench.yml
With this PR we will now update the Prometheus labels after the creation of the new vitess cluster (if new one), allowing for cleaner statistics.
=> Change Prometheus labels right before running macrobenchmark

go/exec/exec.go, go/server/api.go
Fixes https://github.com/vitessio/arewefastyet/issues/521
```
[GIN] 2024/04/02 - 14:53:00 | 200 |  788.178958ms |             ::1 | GET      "/api/recent"
[GIN] 2024/04/02 - 14:53:01 | 200 |   94.367042ms |             ::1 | GET      "/api/recent"
[GIN] 2024/04/02 - 14:53:02 | 200 |   93.952292ms |             ::1 | GET      "/api/recent"
[GIN] 2024/04/02 - 14:53:03 | 200 |  182.713041ms |             ::1 | GET      "/api/recent"
[GIN] 2024/04/02 - 14:53:04 | 200 |  179.287459ms |             ::1 | GET      "/api/recent"
```
=> Fix performance issue on the status page

ansible/roles/sysbench/tasks/install.yml
I think someone changed the default branch of https://github.com/planetscale/sysbench without me knowing, leading to `master` not being usable any more. This PR fix the failures in all recent benchmark by fetching sysbench from main.
=> Fix the branch used by sysbench

go/server/cron.go, go/server/cron_handlers.go
Just a quick fix on how we detect new benchmarks for release branches.
=> Fix how we detect release-branches

ansible/roles/vttablet/templates/vttablet.conf.j2, go/exec/exec.go, go/infra/ansible/vars.go, go/tools/git/git.go
This PR fixes an issue we had since the release of `v20.0.0-rc1` in our `v19` benchmarks. Some of the flag were not using the proper formatting. This was fixed by changing the Jinja template to read an int that corresponds to the major version of vitess we are trying to benchmark, instead of using the non-scalable `is_latest` and `v_xx` from before.
=> Fix flag issues with v19 benchmarks

website/package.json, website/src/assets/styles/tailwind.css, website/src/common/Navbar.tsx, website/src/pages/HistoryPage/HistoryPage.tsx, website/src/pages/HistoryPage/components/Hero.tsx, website/src/pages/PublicRoute.tsx, website/yarn.lock
Refactor the navbar to match the new figma design.
Fix responsive issues as well
-  Related to #558  
-  Others? 
**Summary**
=> Refactor navbar

website/src/common/Footer.tsx
Refactor the footer to match the new figma design.
-  Related to #558 
**Summary**
=> Refactor footer

go/server/api.go
Add the abilty to request for specific workloads 
-  Related to #558  
**Summary**
=> Feat filter-summary-per-workload

website/src/pages/DailyPage/components/DailyCharts.tsx
Quick update as to how the text in the charts' legends look like.
**Before**
**After**
=> Improve the text in the charts' legends

website/src/common/MacroBenchmarkTable.tsx, website/src/pages/ComparePage/ComparePage.tsx, website/src/pages/StatusPage/components/PreviousExecutions/Columns.tsx
This PR adds more content to the metrics latency and errors of the compare page so they are more understandable by anyone and does a quick rename of some of the status' column.
=> Improve understandability of metrics and column names

website/src/pages/StatusPage/components/PreviousExecutions/Columns.tsx
The status page was showing the wrong value for the finished at column, this fixes it.
=> Use the proper value in the finished at column of status

website/src/pages/StatusPage/components/PreviousExecutions/Columns.tsx
Something went wrong in my last PR (#580) and it started showing unfinished benchmark as 00000 Unix timestamp, this PR fixes it by showing "N/A" if the benchmark does not have a finished at value:
=> Fix how we handle unfinished execution

docs/arewefastyet_api.md, docs/arewefastyet_exec.md, docs/arewefastyet_gen_exec_metrics.md, docs/arewefastyet_macrobench_run.md, docs/arewefastyet_microbench_run.md, go/cmd/exec/exec.go, go/cmd/gen/metrics/exec.go, go/cmd/macrobench/run.go, go/cmd/microbench/run.go, go/exec/exec.go, go/exec/metrics/metrics.go, go/exec/pull_request.go, go/exec/status.go, go/storage/mysql/mysql.go, go/storage/psdb/psdb.go, go/storage/storage.go, go/tools/macrobench/config.go, go/tools/macrobench/sql.go, go/tools/macrobench/vtgate.go, go/tools/microbench/line.go, go/tools/microbench/microbench.go, go/tools/microbench/results.go
This PR changes how we read and write to our MySQL database. Since we use PlanetScale DB as our MySQL storage, I have changed our connection logic to now connect to both a read-only and the primary server. The read-only connection pool will now be used for all our select queries. On top of that I have finally added some settings to our connection pool that will prevent it from opening hundreds of connections. I have tested this end-to-end with the PlanetScale DB UI, and reads are well directed to the read-only nodes, and the connections disconnect properly after 3 minutes.
=> Read from read-only MySQL servers

go/storage/psdb/psdb.go
Small issue showed up after merging #588 where we were not assigning the flags to the proper variables when reading config with viper.
=> Fix setting replica username/password with viper

go/server/api.go, go/tools/macrobench/macrobench.go, go/tools/macrobench/results.go, go/tools/macrobench/sql.go, go/tools/macrobench/stats.go
This PR revamps some of our endpoints that get and compare results. The performance were really poor, with for instance a 20 seconds response time for the compare benchmark page, and 25 seconds for the daily results. The response time of these two endpoints was reduced by 88% and 99% on average.
**Before**
```
[GIN] 2024/07/25 - 19:19:40 | 200 | 23.598892375s |             ::1 | GET      "/api/daily?workload=oltp"
[GIN] 2024/07/25 - 19:20:03 | 200 |   23.0457765s |             ::1 | GET      "/api/daily?workload=oltp"
[GIN] 2024/07/25 - 19:20:22 | 200 | 19.204524417s |             ::1 | GET      "/api/daily?workload=oltp"
[GIN] 2024/07/25 - 19:20:24 | 200 | 22.733138458s |             ::1 | GET      "/api/daily?workload=oltp"
[GIN] 2024/07/25 - 19:20:32 | 200 |  19.07924375s | …
```
=> Revamp all our endpoints that get benchmark results

ansible/roles/vtgate/templates/vtgate.conf.j2, ansible/roles/vttablet/templates/vttablet.conf.j2
=> Fix ansible when no profile configure is given

go/admin/templates/add_new_executions.html
We were sending the wrong values when selecting a binary to profile in the admin.
=> Fix the value of the binary to profile in the admin

go/server/api.go, go/server/cron_handlers.go, go/tools/git/git.go, go/tools/git/git_test.go
For the longest time we have only benchmarked and shown the last 3 supported releases of vitess. We want to keep doing the former, and change to 2 releases after v20.0 is EOL because of https://github.com/vitessio/enhancements/pull/12. But we want to change the latter: as soon as a new release is out, we use to stop displaying the results of the oldest major release on the website. When we released v21.0, v18.0 was now 4 major versions behind main, meaning it wouldn't be shown on the website.
With this PR, we are now displaying all versions of vitess that were benchmarked with a compatible method than the one currently used by arewefastyet. Meaning, that if in the future, when e.g. v21.0 is the current latest version of Vitess, we change the methodology of arewefastyet enough that it …
=> List all compatible version of vitess that were benchmarked

go/admin/api.go, go/admin/templates/add_new_executions.html, go/admin/templates/clear_queue.html, go/server/api.go, go/server/cron.go
This Pull Request adds an option to the admin UI to allow users to not remove admin executions from the queue. This will be particularly useful when spawning a bunch of admin executions and wanting them to be prioritized when new executions are created by the cron mechanism.
=> Option to not remove admin executions from the queue

go/cmd/api/api.go, go/server/cron_execution.go
This PR enables the queue watched to always run admin executions first, with the highest priority.
Fixes https://github.com/vitessio/arewefastyet/issues/618
=> Run admin benchmark with the highest priority

go/exec/exec.go, go/exec/status.go, go/server/api.go, go/tools/macrobench/sql.go, website/src/pages/StatusPage/components/ExecutionQueue/Columns.tsx, website/src/pages/StatusPage/components/ExecutionQueue/Execution.tsx, website/src/pages/StatusPage/components/PreviousExecutions/Columns.tsx
This Pull Request enhances the SQL schema of our `execution` table to contain information about profiling. This has several benefits: we can ignore profiled benchmarks when doing a comparison, we can show which benchmarks were profiled in the status page.
Preview:
=> Attach profile information to an execution

go/exec/exec.go, go/exec/pull_request.go, go/server/api.go, go/server/cron_execution.go, go/server/cron_handlers.go, go/tools/github/github.go
This PR entirely removes the execution of the `cron_pr_base` benchmarks and instead compares the result of a PR with the most recent cron benchmark on the base branch of the Pull Request.
This will essentially reduce the time needed to benchmark PRs by 50%, which is a major win.
=> Remove `cron_pr_base` cron and compare PRs with most recent cron

go/admin/api.go, go/admin/templates/add_new_executions.html, go/server/api.go, go/tools/git/github.go, go/tools/git/pulls.go
This PR adds to Admin page a feature to allow Admins to send PR number for benchmarking instead of SHA
=> Allow Admin to add PR to execution queue for benchmarking and profiling

ansible/roles/vitess_build/tasks/main.yml
This fixes an issue that was observed after the recent node/vite versions upgrade https://github.com/vitessio/vitess/pull/17606. When building Vitess we were getting an error from npm:
```
failed to load config from /go/src/vitess.io/vitess/web/vtadmin/vite.config.ts
error during build:
Error: The package "@esbuild/linux-x64" could not be found, and is needed by esbuild.
```
This issue is fixable by removing the local dependencies (`rm -rf node_modules package-lock.json`) and re-installing them (`npm install`).
However, we don't actually need to build vtadmin in arewefastyet so let's skip its build altogether.
=> Skip vtadmin build

ansible/roles/vitess_build/tasks/main.yml
This PR removes an unrequired build of vitess in the ansible steps.
=> Remove unwanted vitess build

website/src/common/MacroBenchmarkTable.tsx
Small fix to the error row in the benchmark comparison table
here the error delta should be green
=> fix color of the error badge when comparing two benchmarks
