.gitignore

Added JetBrain's `.idea` to the `.gitignore`.

Addition .idea to gitignore

---

ansible/oltp_read_write.yml
ansible/roles/vtgate/defaults/main.yml
ansible/roles/vtgate/tasks/cleanup.yml
ansible/roles/vttablet/defaults/main.yml
ansible/roles/vttablet/tasks/cleanup.yml
ansible/tpcc.yml

Stop recording profiles by sending USR1 to Vitess servers.

Write pprof by sending signal to profiled vitess servers

---

.gitignore
infra/terraform/main.tf
infra/terraform/output.tf
infra/terraform/variables.tf
infra/terraform/versions.tf

Relates to #76 by introducing the basic required configuration to start an Equinix Metal device with Terraform.

Addition of sample Equinix Terraform create node

---

ansible/microbench.yml
ansible/microbench_inventory.yml
ansible/roles/host/tasks/install_deps.yml
ansible/roles/microbench/defaults/main.yml
ansible/roles/microbench/tasks/main.yml
ansible/roles/vitess_build/tasks/install_vitess.yml

This pull request contains changes to enable microbenchmarks on a remote host configured by Ansible.
Mainly, a new ansible role has been added: `microbench`. The role will:
- setup Golang
- download the Vitess and Arewefastyet repositories given specific git versions
- fetch microbenchmarks configuration
- execute the microbenchmarks given a Vitess package
The third step _"fetch microbenchmarks configuration"_ will copy the configuration file that's located at `microbenchmarks_local_config` (variable defined in `./ansible/microbench_inventory.yml`).
The changes made in this PR are not yet included in the Go CLI, making testing for the first time a bit longer. However, here are some simple steps:
Firstly, you should have a configuration file looking like this:
> Note that all of these …

Configure infra with Ansible to execute Microbenchmarks

---

go.mod
go.sum
go/server/templates/microbench.tmpl
go/tools/microbench/results.go
go/tools/microbench/results_test.go

try to make numbers easier to read

---

.github/CODEOWNERS

Adding @GuptaManan100 to the `CODEOWNERS` list.

Adding Manan to CODEOWNERS

---

sql/migration/002_add_foreign_key_to_microbenchmark_details.sql
sql/migration/test_migration.sh
sql/vitess-benchmark.sql

*Description*
adds foreign key to microbenchmark details
*Linked Issues*
Resolves #156

added foreign key to microbenchmark details

---

docs/README.md
docs/arewefastyet.md
docs/arewefastyet_exec.md
docs/arewefastyet_gen.md
docs/arewefastyet_gen_doc.md
docs/arewefastyet_gen_report.md
docs/arewefastyet_infra.md
docs/arewefastyet_infra_create.md
docs/arewefastyet_infra_create_equinix.md
docs/arewefastyet_macrobench.md
docs/arewefastyet_macrobench_run.md
docs/arewefastyet_microbench.md
docs/arewefastyet_microbench_run.md
docs/arewefastyet_web.md
go/cmd/exec/exec.go
go/cmd/gen/doc/doc.go
go/cmd/gen/gen.go
go/cmd/gen/report/report.go
go/cmd/infra/create.go
go/cmd/infra/infra.go
go/cmd/macrobench/macrobench.go
go/cmd/macrobench/run.go
go/cmd/microbench/microbench.go
go/cmd/microbench/run.go
go/cmd/root.go
go/cmd/web/web.go

Adds descriptive documentation for the command line interface

Adds descriptive documentation for the command line interface

---

go/exec/exec.go
go/server/handlers.go
go/server/server.go
go/server/templates/macrobench.tmpl
go/server/templates/navigation.tmpl

This PR adds a new section to the website which allows comparison of macrobenchmarks on releases just like the macrobenchmarks.
Resolves #186

Compare MacroBenchmarks of releases like Microbenchmarks

---

go/server/cron.go

Addition of a cron job pool to queue executions one by one, and new corn job for execution on new recent tags.
Resolves #203.

Addition of a CRON execution pool and job for tags

---

go/exec/exec.go
go/server/cron.go
go/tools/git/github.go

This pull request proposes the changes needed to compare pull requests to their base's ref instead of comparing them with the last execution of the same source.
Fixes #221.

Use PR's base ref and compare against them

---

go/server/cron.go
go/server/handlers.go
go/tools/macrobench/compare.go
go/tools/macrobench/macrobench.go
go/tools/macrobench/results.go

Make V3 default and Fix Home page
Fixes #219

Make V3 default and Fix Home page

---

go/server/handlers.go
go/server/server.go
go/server/templates/navigation.tmpl
go/server/templates/v3VsGen4.tmpl
go/tools/macrobench/compare.go

This PR adds an additional page to the website which compares V3 and Gen4 planners.
Fixes #224

V3 vs Gen4 Comparison page

---

docs/arewefastyet_gen.md
docs/arewefastyet_gen_exec_metrics.md
go/cmd/gen/gen.go
go/cmd/gen/metrics/exec.go

This pull request adds a script that, for all execution, fetches its metrics from influxDB and stores them to SQL if they are not already present.

Addition of a script to migrate execution metrics from influxDB to SQL

---

go/server/templates/compare.tmpl
go/server/templates/microbench.tmpl
go/tools/microbench/results.go
go/tools/microbench/results_test.go

This pull request fixes the rendering of microbenchmark results by reordering the column properly.

Fix order on which we display microbenchmark results

---

go/tools/macrobench/results.go
go/tools/microbench/results.go

This pull request avoids the rendering of results if their benchmark is not marked as `finished`.

Not rendering results if their benchmark is not marked as finished

---

.github/workflows/golang_build.yaml
.github/workflows/golang_lint.yaml
.github/workflows/golang_tidy.yaml
.github/workflows/golang_unit_test.yaml
.github/workflows/verify_cli_documentation.yml
go.mod
go.sum

This pull request upgrades the golang version used by this project from `Go1.15` to `Go1.17`.

Upgrade golang version to Go1.17

---

go/server/server.go

This pull request sets the mode on which Gin will run.

Set Gin's server mode

---

.github/workflows/ansible-lint.yml
.github/workflows/deploy.yml
.github/workflows/golang_build.yaml
.github/workflows/golang_lint.yaml
.github/workflows/golang_tidy.yaml
.github/workflows/golang_unit_test.yaml
.github/workflows/verify_cli_documentation.yml
ansible/roles/vitess_build/defaults/main.yml
go.mod
go.sum

This pull request upgrades the Go version to `1.18`.

Upgrade to Go 1.18

---

ansible/roles/vtctld/templates/cell@.service.j2
ansible/roles/vtctld/templates/vtctld@.service.j2
ansible/roles/vtgate/templates/vtgate.conf.j2

Correct flag usage for vtctld and vtgate

---

ansible/roles/vtctld/tasks/ensure.yml

Clean up the ensure primary phase

---

ansible/roles/vitess_build/defaults/main.yml

Upgrade the go version to 1.18.5

---

supervisor/supervisord.conf

This PR changes the supervisord configuration to run the web server using the latest configuration and secret files.

Change supervisord configuration to use the latest configuration files

---

config/benchmarks/olap-readonly.yaml
config/benchmarks/oltp-readonly-olap.yaml
config/benchmarks/oltp-readonly.yaml
go/server/server.go
go/tools/macrobench/types.go

This PR adds read only benchmark with workload `oltp` and `olap`

added oltp read only workload benchmark

---

config/dev/config.yaml
config/prod/config.yaml

This PR enables the production mode of the server when it is run in production.

Enable the `production` mode in production environment

---

ansible/roles/vttablet/templates/vttablet@.service.j2

This PR replaces the deprecated dbconfig flags by the new proper flags for latest and v15 benchmarks.

Removed deprecated vttablet dbconfig flags

---

go/exec/metrics/metrics.go
go/tools/macrobench/results.go

The difference % was incorrect, this PR fixes it.

Fix incorrect difference calculation

---

.gitignore
config/dev/config.yaml
website/.env.dev
website/package-lock.json
website/package.json
website/src/App.jsx
website/src/components/ExecutionQueue/ExeQueue.jsx
website/src/components/PreviousExecutions/PreviousExe.jsx
website/src/components/PreviousExecutions/previousexe.css
website/src/components/footer/footer.css
website/src/components/header/Header.jsx
website/src/components/header/header.css
website/src/index.css
website/src/pages/Home/Home.jsx
website/src/pages/Home/home.css
website/src/pages/Status/Status.jsx
website/src/pages/Status/status.css
website/vite.config.js

I have created a page status that consists of two components: "Previous Executions" and "Execution Queue," which are displayed as two tables on the page. To achieve this, I utilized two libraries: moment.js for date formatting and react-spinner to display a loading indicator while waiting for the API response.

Status page desktop version 

---

website/index.html
website/package-lock.json
website/package.json
website/src/components/PreviousExeResponsive/PreviousExeRes.jsx
website/src/components/PreviousExeResponsive/previousExeRes.css
website/src/components/PreviousExecutions/PreviousExe.jsx
website/src/components/PreviousExecutions/previousexe.css
website/src/pages/Status/Status.jsx
website/src/pages/Status/status.css

I have created a component for the mobile format of the previous executions table and adapted the entire status page for tablet and mobile formats.

Responsive design of the status page, creating a "PreviousExecutionsMobile" component tailored for mobile format.

---

website/src/utils_/Error.jsx
website/src/utils_/error.css

I have created an error page for when a person searches a non-existent route. They will encounter an error message with a 404 code and a link that redirects them to the Home page.

[Feature] Added 404 Error Page for Non-Existent Routes

---

README.md

This PR updates the main README of the repository with a proper description. This is a follow up of the work done in https://github.com/vitessio/website/pull/1340.

Update the main README of repository

---

config/dev/config.yaml
go/server/api.go
go/server/server.go

I have created a route for the search page that captures micro and macro.

Create Api Search

---

website/src/components/StatusComponents/PreviousExecutions/previousexe.css
website/src/pages/Compare/Compare.jsx
website/src/pages/Search/Search.jsx
website/src/pages/Status/Status.jsx
website/src/pages/Status/status.css
website/src/utils/Hook.jsx

I have created a hook for API calls in the frontend. Here is a detailed explanation of how this hook works:
Dependency import: The hook utilizes the necessary dependencies from React, namely useState and useEffect, as well as importing the errorApi utility from the Utils file.
Hook definition: The hook is a function named useApiCall that takes a URL as a parameter. This URL is used to make the API call.
State initialization: The hook uses three states with useState.
data is initialized with an empty array ([]) and will be used to store the data retrieved from the API.
isLoading is initialized as true and indicates whether the data is currently being loaded from the API.
error is initialized as null and will be used to store any errors that occur during the data retrieval from the API. …

Introducing the useApiCall hook for frontend API calls

---

website/package-lock.json
website/package.json
website/src/components/MacroComponents/Macrobench/Macrobench.jsx
website/src/components/MacroComponents/Macrobench/macrobench.css
website/src/components/MacroComponents/MacrobenchMobile/MacrobenchMobile.jsx
website/src/components/MacroComponents/MacrobenchMobile/macrobenchmobile.css
website/src/components/Microbench/Microbench.jsx
website/src/components/QueryPlan/QueryPlan.jsx
website/src/components/QueryPlan/queryPlan.css
website/src/pages/Macro/Macro.css
website/src/pages/Macro/Macro.jsx
website/src/pages/MacroQueriesCompare/MacroQueriesCompare.jsx
website/src/pages/MacroQueriesCompare/macroQueriesCompare.css
website/src/pages/PublicRoute.jsx
website/src/utils/Utils.jsx

A link is added to the macro page to navigate to a new page called 'macrobench query plan'. Then, I called the API and created a component for each SQL query to optimize the readability of the information.
Closes https://github.com/vitessio/arewefastyet/issues/390

Creation of the macrobenchQueryPlan page and its queryPlan component

---

go/exec/pull_request.go
go/server/api.go
go/server/server.go
website/src/components/PRcomponents/PRGitInfo.css
website/src/components/PRcomponents/PRGitInfo.jsx
website/src/components/header/Header.jsx
website/src/index.css
website/src/pages/Compare/compare.css
website/src/pages/PR/PR.css
website/src/pages/PR/PR.jsx
website/src/pages/PublicRoute.jsx
website/src/pages/Status/status.css
website/src/utils/Utils.jsx

I have created two new API routes to retrieve the pull numbers and their git refs, and I have created a PR page to be able to directly redirect to the compare page with the pull request's git ref and the git ref of main as arguments.

Enhanced Pull Request Routing: Retrieving Pull Numbers and Git Refs

---

config/dev/config.yaml
go/server/api.go
go/server/cron.go
go/server/cron_execution.go
go/server/cron_handlers.go
go/server/templates/status.tmpl

Reverts vitessio/arewefastyet#400

Revert "Use `slice` instead of map for the execution queue"

---

website/src/components/PRcomponents/PRGitInfo.css
website/src/components/PRcomponents/PRGitInfo.jsx
website/src/index.css
website/src/pages/PR/PR.css
website/src/pages/PR/PR.jsx

I took the status page template to make it mobile and tablet responsive, which means having the information as clear as possible.

Responsive mobile & tablet PullRequest Page

---

website/src/components/header/Header.jsx
website/src/components/header/header.css

I tried to change the light and dark mode icons. They are bit similar to the earlier one. I changed the position of that toggle button as the latter seemed more user-friendly. I am attaching the demo video of my current changes.
https://github.com/vitessio/arewefastyet/assets/76479104/3e524d68-36f0-484c-8f53-dea64abe0401
Or we can have a slider-type toggle button. Image attached.
Do let me know your thoughts about it.

light-dark mode toggle button changed

---

website/src/components/DailyComponents/DailySummary/DailySummary.jsx
website/src/components/MacroComponents/MacrobenchMobile/macrobenchmobile.css
website/src/components/SearchComponents/SearchMacro/SearchMacroDesktop/searchMacroDesktop.css
website/src/components/SearchComponents/SearchMacro/SearchMacroMobile/searchMacro.css
website/src/index.css
website/src/pages/Daily/Daily.jsx
website/src/pages/Daily/daily.css
website/src/pages/Home/Home.jsx
website/src/pages/Home/home.css
website/src/pages/Macro/Macro.css
website/src/pages/PR/PR.css
website/src/pages/Search/search.css
website/src/pages/Status/status.css

I fixed display bugs on certain pages of the website and implemented the selection of cronSummary when sharing the URL.

Fixing Display Bugs and Implementing cronSummary URL Selection

---

website/src/pages/Search/Search.jsx
website/src/pages/Search/search.css

I have redesigned the search bar in the search page for the frontend.  I have also added a small focus animation on the search bar.

Added ui enhancement to the search bar in search

---

config/dev/config.yaml
package-lock.json
website/package-lock.json
website/src/components/DailyComponents/DailySummary/DailySummary.jsx
website/src/components/DailyComponents/DailySummary/dailySummary.css
website/src/components/Microbench/Microbench.jsx
website/src/components/SearchComponents/SearchMacro/SearchMacroDesktop/searchMacroDesktop.css
website/src/components/SearchComponents/SearchMacro/SearchMacroMobile/SearchMacro.jsx
website/src/components/SearchComponents/SearchMacro/SearchMacroMobile/searchMacro.css
website/src/components/footer/footer.css
website/src/index.css
website/src/pages/Compare/compare.css
website/src/pages/Daily/Daily.jsx
website/src/pages/Daily/daily.css
website/src/pages/PR/PR.css
website/src/pages/Search/search.css

Fix responsive 

---

website/src/pages/Compare/Compare.jsx
website/src/pages/Compare/compare.css

Added the same focus effect as of Search page input bar, on compare page input bars

Added Ui enhancement to the input bar on compare page

---

Dockerfile
Dockerfile.ghapp
ansible/roles/vitess_build/defaults/main.yml
config/dev/config.yaml
config/prod/config.yaml
go.mod
go.sum

bump arewefastyet api and ghapp to go1.21

---

go/server/server_test.go
go/tools/macrobench/results_test.go

Fix various unit tests

---

config/prod/config.yaml
go/server/cron_handlers.go
go/server/server.go

this should be reverted once testing is done

wip test pr perf

---

website/src/common/Footer.jsx
website/src/common/Navbar.jsx
website/src/pages/HomePage/HomePage.jsx
website/src/pages/HomePage/components/Hero.jsx
website/src/pages/HomePage/components/HeroMobile.jsx
website/src/pages/HomePage/components/HowItWorks.jsx

partially addresses #500 
Adds mobile-friendly footer and navbar and makes the landing page more mobile responsive. Also removes the functionality of the navbar hiding on scroll down temporarily.
This is mostly patchwork but its a start
https://github.com/vitessio/arewefastyet/assets/14011425/476865cb-b06e-46d5-a69b-4ceac28f4901

feat: Make landing page mobile responsive

---

ansible/macrobench_unsharded_inventory.yml
ansible/roles/vttablet/tasks/clean.yml
config/benchmarks/tpcc_fk.yaml
config/benchmarks/tpcc_fk_unmanaged.yaml
config/benchmarks/tpcc_unsharded.yaml
go/server/server.go

This PR also include a wip to remove the OLTP benchmarks as I am debugging the TPCC benchmarks right now. The wip commit will be reverted.

Unsharded benchmarks with two vttablets and a smaller TPCC scale

---

website/src/common/DisplayList.tsx
website/tailwind.config.ts

Make the status table mobile responsive
[Screencast from 23-04-24 02:29:13 AM IST.webm](https://github.com/vitessio/arewefastyet/assets/127925465/0a66ad01-27cd-4f88-bcc4-dfe8d6fa83c0)
Related to #500

feat: make the table of status page responsive

---

website/src/common/Footer.tsx

Replaced the twitter logo with the new  X logo 
Changes Done in file :  `website/src/common/Footer.tsx`
What changes are done: Replaced  "AiFillTwitterCircle" with "FaSquareXTwitter". 
closes #530 
**Screenshot**
| Before | After | 
| ---------| --------|
| ![Screenshot from 2024-04-26 19-00-32](https://github.com/vitessio/arewefastyet/assets/124715224/1d876648-a726-46d4-9f15-defedfa744be) |  ![image](https://github.com/vitessio/arewefastyet/assets/124715224/de85281f-898d-47b6-a382-1ea2319fb55e)        |

Feat: Replacing twitter logo with new X logo

---

website/src/pages/SearchPage/components/Hero.tsx
website/src/pages/SearchPage/components/SearchMacro.tsx

Search Page files were throwing type errors since the  types were not defined which are now resolved by adding relevant types to  the files. 
Files Changed:
1. `website/src/pages/SearchPage/components/Hero.tsx`
2. `website/src/pages/SearchPage/components/SearchMacro.tsx`

Adding types in SearchPage

---

website/src/pages/StatusPage/components/PreviousExecutions.tsx

Removing type error from the file `PreviousExecutions.tsx`
N/A
N/A
**Summary**
Type error in this file is now fixed.

Fix: Removing type errors

---

website/src/common/DisplayList.tsx
website/src/common/Footer.tsx
website/src/common/Modal.tsx
website/src/common/Navbar.tsx

Added types for DisplayList.tsx, Footer.tsx, Navbar.tsx

Added types for common folder

---

go/exec/status.go

Retrieve all benchmarked commits and number of workloads done per day for the last 7 days   
-  Related to #558  
**Summary**

Feat commits and past 7 days

---

website/src/pages/Layout.tsx

Make the footer stick to the bottom if the page
-  Others? 
|![image](https://github.com/user-attachments/assets/75e1aa91-d714-4ab5-90ce-c04b733f0a7b)|![image](https://github.com/user-attachments/assets/cd4778a6-d9b5-4755-933a-1e1cd9ab8013)|   
**Summary**

Fix footer

---

go/server/api.go

Removing an extra logging we do not need.

Remove unrequired logging

---

website/src/pages/StatusPage/components/ExecutionQueue/Execution.tsx

Made execution queue table wider on mobile.
-  Others? 
|![image](https://github.com/user-attachments/assets/f61b9c0c-9d8d-4e70-8aa3-c81edf87bb2f)|![image](https://github.com/user-attachments/assets/f1dc6d14-018a-48c9-a181-34ffcd7cfb77)|   
**Summary**

Fix Execution queue table responsiveness

---

go/server/api.go
go/server/server.go
go/tools/macrobench/vtgate.go

New api route that compares queris for FK
-  Others? 
**Summary**

Feat FK queries compare

---

website/src/pages/PRPage/PRPage.tsx
website/src/pages/PRsPage/PRsPage.tsx
website/src/pages/PRsPage/components/Columns.tsx
website/src/pages/PRsPage/components/PRTable.tsx
website/src/pages/PRsPage/components/PRTableToolbar.tsx

Fix PR and PRs page

---

go/exec/exec.go
go/server/api.go
go/server/server.go
website/src/pages/HistoryPage/HistoryPage.tsx
website/src/pages/HistoryPage/components/Columns.tsx
website/src/pages/HistoryPage/components/HistoryHero.tsx
website/src/pages/HistoryPage/components/HistoryTable.tsx
website/src/pages/HistoryPage/components/HistoryTableToolbar.tsx

Feat History Page

---

website/package.json
website/src/App.tsx
website/src/common/CompareActions.tsx
website/src/common/CompareActionsWrapper.tsx
website/src/common/CompareRowActions.tsx
website/src/components/ui/toast.tsx
website/src/components/ui/toaster.tsx
website/src/components/ui/use-toast.ts
website/src/contexts/CompareContext.tsx
website/src/pages/ComparePage/components/CompareHero.tsx
website/src/pages/HistoryPage/components/Columns.tsx
website/src/pages/Layout.tsx
website/src/pages/StatusPage/components/PreviousExecutions/Columns.tsx
website/yarn.lock

https://github.com/user-attachments/assets/50428bbc-2c41-49ef-9edd-86340a8a85a0
-  Others? 
**Summary**

Feat add to compare

---

website/src/common/CommandMenu.tsx
website/src/common/CompareRowActions.tsx
website/src/common/Navbar.tsx
website/src/components/ui/command.tsx
website/src/pages/HistoryPage/HistoryPage.tsx
website/src/pages/HistoryPage/components/HistoryTable.tsx
website/src/pages/HistoryPage/components/HistoryTableToolbar.tsx
website/src/pages/Layout.tsx

Feat search

---

website/src/pages/PRPage/PRPage.tsx

Feat display no base or head and disable button

---

website/src/pages/ForeignKeysPage/ForeignKeysPage.tsx

Refactor use sha instead of tag in fk page url

---

go/tools/macrobench/results.go
go/tools/macrobench/stats.go
website/src/common/CompareActions.tsx
website/src/common/MacroBenchmarkTable.tsx
website/src/pages/ComparePage/ComparePage.tsx
website/src/pages/ComparePage/components/CompareHero.tsx
website/src/pages/ForeignKeysPage/ForeignKeysPage.tsx
website/src/types/index.ts
website/src/utils/Hook.tsx
website/src/utils/Utils.tsx

This PR enhances the compare page functionality by implementing URL naming, improving column titles, adding a shortcut for the compare button, enhancing the API for the compare route, and optimizing the initial load of the compare page. These changes aim to improve usability and clarity when comparing releases, branches, or commits.
The URL for the compare page now uses release names (for releases) instead of commit SHAs. This makes links more intuitive and predictable, especially useful for drafting blog posts about upcoming releases.
The titles of the old and new columns on the compare page now display the release or branch name when selected from the dropdown. If a commit SHA is entered directly, it is displayed in the column titles. …

Feat Compare and Foreign Keyspages enhancement

---

website/index.html
website/package.json
website/src/App.tsx
website/yarn.lock

Add google analytics

---

website/src/pages/StatusPage/components/StatusHero.tsx

-  Others? 
|![image](https://github.com/user-attachments/assets/ffb6ca21-b353-4e07-a7aa-02bf4fcc37ea) | ![image](https://github.com/user-attachments/assets/3006831b-86a6-4194-b38b-4d3225575c0b)|   
**Summary**

fix: status hero error

---

.gitignore
go/admin/api.go

fix: check both maintainer and arewefastyet team admin

---

config/prod/config.yaml

Small fix to the admin's config

Fix production mode admin

---

ansible/macrobench_sharded_inventory.yml
ansible/macrobench_unsharded_inventory.yml
ansible/microbench_inventory.yml

Small fix to which storage device we are using to mount the `/vt` directory.

Fix disk storage device name

---

go/admin/templates/add_new_executions.html

fix profile modes
